name: Publish Helm Charts
on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.*"
    paths:
      - charts/**
env:
  REGISTRY: ghcr.io
jobs:
  build-and-publish-chart:
    name: Build and publish Helm Charts
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4
        with:
          version: v3.17.4
      - name: Log in to the Container registry
        run: "helm registry login ${{ env.REGISTRY }}/${{ github.actor }}/charts -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}"
      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version-file: "go.mod"

      - name: Build and publish # replace with pre-built binary
        run: "go run cmd/updater/main.go --mode=publish"
