name: Publish Helm Charts
on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.*"
    paths:
      - charts/**
env:
  REGISTRY: ghcr.io
jobs:
  build-and-publish-chart:
    name: Build and publish Helm Charts
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4
        with:
          version: v3.17.4
      - name: Log in to the Container registry
        run: "helm registry login ${{ env.REGISTRY }}/${{ github.actor }}/charts -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}"
      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version-file: "go.mod"

      - name: Build and publish # replace with pre-built binary
        run: "go run cmd/updater/main.go --mode=publish"
